// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("MassTransit.Autofac.StateMachineSagas")]
[assembly: AssemblyCompanyAttribute("Alexey Zimarev")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2016 Alexey Zimarev")]
[assembly: AssemblyVersionAttribute("3.3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.3.0.0")]
[assembly: AssemblyInformationalVersionAttribute("3.3.0-unstable.9+Branch.develop.Sha.64831034b1fb785d8d4f6f7c1a6dd73b2bc65650")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.3.0.0";
        internal const string InformationalVersion = "3.3.0-unstable.9+Branch.develop.Sha.64831034b1fb785d8d4f6f7c1a6dd73b2bc65650";
    }
}
