// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("MassTransit.Autofac.StateMachineSagas")]
[assembly: AssemblyCompanyAttribute("Alexey Zimarev")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2016 Alexey Zimarev")]
[assembly: AssemblyVersionAttribute("3.3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.3.0.0")]
[assembly: AssemblyInformationalVersionAttribute("3.3.0-unstable.10+Branch.develop.Sha.f724654caba6efddb9d7c63818c5b2b516776e4b")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.3.0.0";
        internal const string InformationalVersion = "3.3.0-unstable.10+Branch.develop.Sha.f724654caba6efddb9d7c63818c5b2b516776e4b";
    }
}
